### ISSUE TITLE
LottieAnimationView getConstants did not have a corresponding prop

### ISSUE THREAD

**Issue by mrigo** [lottie-react-native/lottie-react-native#502]
### Description

The warning appears upgrading react native to 0.59.9

### Steps to Reproduce

1. Use react-native 0.59.9
2. npm i lottie-react-native
3. Run the application

**Expected behavior:** 
No warning

**Actual behavior:**
```
ReactNative.NativeModules.LottieAnimationView.getConstants did not have a corresponding prop defined
in the mock provided to SafeModule.
```

### Versions

react-native-cli: 2.0.1
react-native: 0.59.9
lottie-react-native: 2.6.1
lottie-ios: 2.5.0

**Comment by xhirazi** [comment]
+1

**Comment by goriverna** [comment]
+ 1

**Comment by kuzyakiev** [comment]
+1

**Comment by Speariv35** [comment]
+1

**Comment by SergeyYuhimovich** [comment]
+1

**Comment by slushman** [comment]
Looks like this was fixed for version 3.1.0 and newer, but all of us on v2.6.1 are stuck for now.

https://github.com/react-native-community/lottie-react-native/commit/f642dde396f2377f00430a91538bb033d9828f45#diff-6229aa3fed4aa97b8e7c88070edfddd5

**Comment by brandtnewww** [comment]
As a workaround, you could do the following in your App.js:

```
import { YellowBox } from 'react-native'
YellowBox.ignoreWarnings(['ReactNative.NativeModules.LottieAnimationView'])
```

**Comment by danielmtavares** [comment]
A better workaround is to just apply the change mentioned by @slushman instead of ignoring the warning.

**Comment by connorpmullins** [comment]
I'm running into a similar issue
![image](https://user-images.githubusercontent.com/24562987/88109550-9330c500-cb5f-11ea-926d-061abb8d6129.png)

react-native: 0.61.4
lottie-react-native: 3.4.0
lottie-ios: 3.1.3

**Comment by connorpmullins** [comment]
Note on my above comment: Looks like there's another open issue reporting .resume and .pause warnings over here: https://github.com/react-native-community/lottie-react-native/issues/662

I'm still getting the same warnings after upgrading to the latest lottie package versions
